### ISSUE TITLE
Derived variables

### ISSUE THREAD

**Issue by gavinhenderson** [AceCentre/aac-launchpad#14]
# User story

As a user I want to be able to set a variable that then in turn does multiple things. For example I might select 'high contrast' which will change a preset group of variables.

# Technical

I would probably do this by adding a variable type that is a select but each option in the select defines a set of other variable values which are referenced in the template.

The variables that are over ridden should be given an option like `hide` so they don't come up so you can only set them via the top level variable

The UI will have to be updated to handle this new data

# Tasks
 - [x] Update schema
 - [x] Add a template
 - [x] Allow presets via CLII
 - [x] Allow presets via API
 - [x] Add the ability to hide variables in the CLI
 - [x] Show presets and hidden variables in the UI
