### ISSUE TITLE
Allow labels out of the boxes

### ISSUE THREAD

**Issue by gavinhenderson** [AceCentre/aac-launchpad#15]
# User story

As a template maker I would like the labels to have the ability to appear below the box

# Details

Currently the labels always appear in the box even when you have an image. We should allow the ability to put the labels under the box. This will have to cascade to the grid calculations

# Tasks

- [x] Setup tests for existing
- [x] Update type
- [x] Build without templatability
- [x] Add boolean variable type
- [x] Template the variable
- [x] Add test
- [x] Update UI to handle booleans
- [x] Test in prod
