### ISSUE TITLE
Add the ability to change font

### ISSUE THREAD

**Issue by gavinhenderson** [AceCentre/aac-launchpad#2]
# User story

As a user I want to be able to create resources that have a specific font that works best for an individual.

# Details

We don't need to have all the fonts ever available, lets only allow fonts that serve a specific use and we should have descriptive information on each font.

Fonts we want to include:
* [‘open dyslexic’](https://opendyslexic.org/)
* [‘atkinson hyperlegible’](https://brailleinstitute.org/freefont)
* Comic sans (for children's resources)

# Technical

It should be easy to add more fonts as they are suggested. By dumping a standard font file into a folder and adding a key to a list.

The frontend should be able to query the fonts. We should also add a new variable type to allow for the front end to have a custom picker rather than a select.

# Tasks

- [x] Allow hardcoded fonts
- [x] Allow templated fonts
- [x] Allow templated fonts via api
- [x] Allow templated fonts via UI
- [x] Document font system
- [x] Add more fonts
- [x] Test all fonts in prod
