### ISSUE TITLE
Images in templates

### ISSUE THREAD

**Issue by gavinhenderson** [AceCentre/aac-launchpad#3]
# User story

As a template creator I want to be able to create a template with an image upload to a cell. It should be optional.

# Technical

We need to allow people to upload images and the attach a reference. We can just save it to disk but it shouldnt be accessible online. 

We should also allow a URL to be provided

# Tasks
 
- [x] Engine can accept local paths
- [x] Engine can accept urls
- [x] Can template images
- [x] Can template images via API
- [x] Create image upload
- [x] Can template images via UI
- [x] Test on live site
